# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Robert Mattila
tagline:          'PhD'
description:      'PhD, Data Scientist' # <br/><a href="https://www.seb.se/">@ SEB Analytics</a>'
url:              http://rmattila.github.io
#baseurl:          /
#Have a look at https://github.com/github/pages-gem/issues/350 to see when the issue is resolved
#baseurl:          'http://rmattila.github.io/'
baseurl:          ''

author:
  name:           'Robert Mattila'
  url:            https://rmattila.github.io

paginate:         10

# Custom vars
cover_image:      /public/me2.png

# separator for teaser and content
excerpt_separator: "<!--more-->"
