# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Robert Mattila
tagline:          'PhD Student'
description:      'PhD Student<br/><a href="http://www.kth.se/ees/omskolan/organisation/avdelningar/ac?l=en_UK">Automatic Control</a><br/>KTH'
url:              http://rmattila.github.io
baseurl:          /
#Have a look at https://github.com/github/pages-gem/issues/350 to see when the issue is resolved
#baseurl:          'http://rmattila.github.io/'

author:
  name:           'Robert Mattila'
  url:            https://rmattila.github.io

paginate:         4

# Custom vars
cover_image:      /public/me2.png

