# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Robert Mattila
tagline:          'PhD Student'
description:      'PhD Student<br/><a href="http://www.kth.se/ees/omskolan/organisation/avdelningar/ac?l=en_UK">Automatic Control</a><br/>KTH'
url:              http://rmattila.github.io
baseurl:          /

author:
  name:           'Robert Mattila'
  url:            https://rmattila.github.io

paginate:         3

# Custom vars
cover_image:      /public/me2.png

